### ISSUE TITLE
what's the mcool file like?

### ISSUE THREAD

**Issue by junmeiW** [ma-compbio/MATCHA#2]
Hi, 
i've read your paper and want to know more about the node-embedding for the hic matrix data, i wonder what the `.mcool` file in the `config.jason` looks like ? can the `.hic` file be converted to `.mcool` file   could u please upload one example? 

I would be very grateful to receive your reply!
Thanks!

**Comment by ruochiz** [comment]
Please see https://cooler.readthedocs.io/en/latest/schema.html?highlight=mcool#multi-resolution for the definition of the `.mcool` file.
For turning the `.hic` file into `.mcool` file, this tool is really helpful: https://github.com/4dn-dcic/hic2cool

All the `.mcool` files used in the MATCHA paper are downloaded from the 4DN data portal: https://data.4dnucleome.org/
