### ISSUE TITLE
How long does the model training take?

### ISSUE THREAD

**Issue by hzjsxu** [ma-compbio/MATCHA#3]
Hi, I've read your paper, it's a wonderful work. And I have 2 questions.
1. I want to know how long does the model training take, i.e how long does it take if run the main.py using SPRITE data (size=3,4,5)? 
2. I downloaded the CHIA-Drop data and found the hyperedges don't corresponding to ones listed in the Table S1 in your paper? Can you provide more information about CHIA-Drop data or share this data you used?

I would be very grateful to receive your reply!
Thanks!

**Comment by ruochiz** [comment]
Thank you for your interest in our work.


It takes about 2 hours to train the model for the SPRITE data at 1Mb using 1 2080Ti GPU card.

For the ChIA-Drop data, if you go to the history_version/data folder of this github repo, you would see the folder named drop, which correspond to the ChIA-Drop data we used. 

The main differences between the downloaded ChIA-Drop data and the hyperedges we used is the binning step. I attached the script I used to do that in the attachment. 
[drop2hyper.txt](https://github.com/ma-compbio/MATCHA/files/8429880/drop2hyper.txt)
